version: '3.8'
services:
  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8002:6000
  queue:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    volumes:
       - ./data_app/MOCK_DATA.json:/usr/src/app/MOCK_DATA.json
    environment:
      URL_NAME: 'amqps://xvgcwhcy:555apjMjsMEzWDB28702DBHNHli64S4Q@beaver.rmq.cloudamqp.com/xvgcwhcy'
      QUEUE_NAME: 'test_queue'
volumes:
    data_app: {} 