version: '3.8'
services:
  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8002:6000
  queue:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    volumes:
       - ./data_app/MOCK_DATA.json:/usr/src/app/MOCK_DATA.json
    environment:
      URL_NAME: 'amqps://yhqizdem:nJGBDLNceVinw90UAxBkIX-65Xw4aTWM@beaver.rmq.cloudamqp.com/yhqizdem'
      QUEUE_NAME: 'test_queue'
volumes:
    data_app: {} 