version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8002:6000
    volumes:
      - .:/app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
