version: '3.8'
services:
  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: 'node src/consumer.js'
    ports:
      - 8082:5001
    volumes:
       - ./data_app/MOCK_DATA.json:/usr/src/app/MOCK_DATA.json
    environment:
      URL_NAME: 'amqps://xvgcwhcy:555apjMjsMEzWDB28702DBHNHli64S4Q@beaver.rmq.cloudamqp.com/xvgcwhcy'
      QUEUE_NAME: 'test_queue2'
volumes:
    data_app: {} 
