version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      URL_NAME: 'amqps://yhqizdem:nJGBDLNceVinw90UAxBkIX-65Xw4aTWM@beaver.rmq.cloudamqp.com/yhqizdem'
      QUEUE_NAME: 'test_queue'
    ports:
      - 8001:5000
    volumes:
      - .:/app

