version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      URL_NAME: 'amqps://xvgcwhcy:555apjMjsMEzWDB28702DBHNHli64S4Q@beaver.rmq.cloudamqp.com/xvgcwhcy'
      QUEUE_NAME: 'test_queue'
    ports:
      - 8001:5000
    volumes:
      - .:/app

